### ISSUE TITLE
Adding HA Proxy creates 503 status

### ISSUE THREAD

**Issue by StephanieSunshine** [tvansteenburgh/meteor-charm#1]
Following the simple instructions on GitHub I can make everything work up until I add haproxy and then I get a 503 status.

```
juju@juju:~$ juju status
environment: manual
machines:
  "0":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju.int.ziphub.com
    instance-id: 'manual:'
    series: precise
    hardware: arch=amd64 cpu-cores=1 mem=991M
    state-server-member-status: has-vote
  "1":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju-1.juju-100.ziphub.com
    instance-id: manual:juju-1.juju-100.ziphub.com
    series: trusty
    hardware: arch=amd64 cpu-cores=1 mem=991M
  "2":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju-2.juju-100.ziphub.com
    instance-id: manual:juju-2.juju-100.ziphub.com
    series: trusty
    hardware: arch=amd64 cpu-cores=1 mem=991M
  "3":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju-3.juju-100.ziphub.com
    instance-id: manual:juju-3.juju-100.ziphub.com
    series: trusty
    hardware: arch=amd64 cpu-cores=1 mem=991M
  "4":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju-4.juju-100.ziphub.com
    instance-id: manual:juju-4.juju-100.ziphub.com
    series: precise
    hardware: arch=amd64 cpu-cores=1 mem=989M
  "5":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju-5.juju-100.ziphub.com
    instance-id: manual:juju-5.juju-100.ziphub.com
    series: precise
    hardware: arch=amd64 cpu-cores=1 mem=991M
  "6":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju-6.juju-100.ziphub.com
    instance-id: manual:juju-6.juju-100.ziphub.com
    series: precise
    hardware: arch=amd64 cpu-cores=1 mem=991M
  "7":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju-7.juju-100.ziphub.com
    instance-id: manual:juju-7.juju-100.ziphub.com
    series: precise
    hardware: arch=amd64 cpu-cores=1 mem=989M
  "8":
    agent-state: started
    agent-version: 1.20.7
    dns-name: juju-8.juju-100.ziphub.com
    instance-id: manual:juju-8.juju-100.ziphub.com
    series: precise
    hardware: arch=amd64 cpu-cores=1 mem=989M
services:
  haproxy:
    charm: cs:precise/haproxy-35
    exposed: true
    relations:
      peer:
      - haproxy
      reverseproxy:
      - meteor
    units:
      haproxy/0:
        agent-state: started
        agent-version: 1.20.7
        machine: "7"
        open-ports:
        - 80/tcp
        - 81/tcp
        public-address: juju-7.juju-100.ziphub.com
      haproxy/1:
        agent-state: started
        agent-version: 1.20.7
        machine: "8"
        open-ports:
        - 80/tcp
        - 81/tcp
        public-address: juju-8.juju-100.ziphub.com
  meteor:
    charm: cs:precise/meteor-2
    exposed: false
    relations:
      mongodb:
      - mongodb
      website:
      - haproxy
    units:
      meteor/0:
        agent-state: started
        agent-version: 1.20.7
        machine: "4"
        open-ports:
        - 3000/tcp
        public-address: juju-4.juju-100.ziphub.com
      meteor/1:
        agent-state: started
        agent-version: 1.20.7
        machine: "5"
        open-ports:
        - 3000/tcp
        public-address: juju-5.juju-100.ziphub.com
      meteor/2:
        agent-state: started
        agent-version: 1.20.7
        machine: "6"
        open-ports:
        - 3000/tcp
        public-address: juju-6.juju-100.ziphub.com
  mongodb:
    charm: cs:trusty/mongodb-3
    exposed: false
    relations:
      database:
      - meteor
      replica-set:
      - mongodb
    units:
      mongodb/0:
        agent-state: started
        agent-version: 1.20.7
        machine: "1"
        open-ports:
        - 27017/tcp
        - 27019/tcp
        - 27021/tcp
        - 28017/tcp
        public-address: juju-1.juju-100.ziphub.com
      mongodb/1:
        agent-state: started
        agent-version: 1.20.7
        machine: "2"
        open-ports:
        - 27017/tcp
        - 27019/tcp
        - 27021/tcp
        - 28017/tcp
        public-address: juju-2.juju-100.ziphub.com
      mongodb/2:
        agent-state: started
        agent-version: 1.20.7
        machine: "3"
        open-ports:
        - 27017/tcp
        - 27019/tcp
        - 27021/tcp
        - 28017/tcp
        public-address: juju-3.juju-100.ziphub.com
juju@juju:~$ 
```
